name = "infiflowx-us"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
run_worker_first = true

[env.production]
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
